# Generated by Django 5.2.7 on 2026-07-21 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0007_alter_equipocliente_alias'),
        ('productos', '0022_producto_vida_util_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='productos.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='organizacion.sucursal')),
            ],
            options={
                'verbose_name': 'Stock de producto',
                'verbose_name_plural': 'Stocks de productos',
                'unique_together': {('producto', 'sucursal')},
            },
        ),
    ]
