# Generated by Django 5.2.7 on 2026-07-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0024_backfill_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='lote',
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
