# Generated by Django 5.2.7 on 2026-08-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0025_remove_lote_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_interno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto', name='sku', field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'activo')),
                fields=('codigo_interno',),
                name='producto_codigo_interno_activo_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'activo')),
                fields=('sku',),
                name='producto_sku_activo_uniq',
            ),
        ),
    ]
