# Generated by Django 5.2.7 on 2026-07-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0016_detallesalida_subtipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoitem',
            name='lote',
        ),
    ]
