# Generated by Django 5.2.7 on 2026-07-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0007_alter_equipocliente_alias'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cliente', unique_together={('rfc', 'activo')},
        ),
    ]
