# Generated by Django 5.2.7 on 2026-07-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0008_alter_cliente_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
