# Generated by Django 5.2.7 on 2026-07-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0009_alter_cliente_rfc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(name='cliente', unique_together=set(),),
    ]
