# Generated by Django 5.2.7 on 2026-07-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0010_alter_cliente_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipocliente',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='equipocliente',
            name='numero_serie',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
