# Generated by Django 5.2.7 on 2026-09-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0011_equipocliente_comentarios_equipocliente_numero_serie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipocliente', unique_together={('cliente', 'equipo', 'numero_serie')},
        ),
    ]
